[package]
name = "dg"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
clap = "2"
fibers = "0.1"
fibers_inotify = "0.1"
fibers_tasque = "0.1"
futures = "0.1"
inotify = "0.5"
trackable = "0.2"